# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'U-Hack!' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for U-Hack!
  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Auth', '~> 4.13.0'
  pod 'Firebase/Database', '~> 4.13.0'

  target 'U-Hack!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'U-Hack!UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
